### ISSUE TITLE
Incorrect credentials make the app fail

### ISSUE THREAD

**Issue by izidormatusov** [getting-things-gnome/GTGOnline#1]
Try to log in with non-existing credentials. You get the following error:

Environment:

Request Method: POST
Request URL: http://gtgonline-parinporecha.rhcloud.com/user/authenticate/

Django Version: 1.5.1
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'demo',
 'Task_backend',
 'Tag_backend',
 'User_backend')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/var/lib/openshift/518740634382ec0f460001d2/python-2.7/virtenv/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/core/handlers/base.py" in get_response
1.                 response = middleware_method(request, response)
   File "/var/lib/openshift/518740634382ec0f460001d2/python-2.7/virtenv/lib/python2.7/site-packages/Django-1.5.1-py2.7.egg/django/middleware/common.py" in process_response
2.         if response.status_code == 404:

Exception Type: AttributeError at /user/authenticate/
Exception Value: 'str' object has no attribute 'status_code'
`

**Comment by parinporecha** [comment]
I've removed the bug.
Also registration has been enhanced to be successful only if -
-> user has entered a valid email
-> email is not already registered
-> passwords match

Please let me know if you find more errors
Closing this issue.
