### ISSUE TITLE
Help: Run as a daemon?

### ISSUE THREAD

**Issue by gangelop** [getting-things-gnome/GTGOnline#14]
Hello. I've just set up GTGOnline with a simple sqlite3 backend. This might be a silly question since I'm unfamiliar with django but...

How do I run this as a daemon, in the background, on boot, like a proper service?

This is a general question but I'm currently setting this up on ubuntu 14.04

**Comment by parinporecha** [comment]
I found a [ticket](https://code.djangoproject.com/ticket/4996) for this on Django's bugzilla which they have closed as 'wontfix'. The developers' opinion is that the development server isn't robust enough to be run as a daemon.

But if you want to run it in the background, there are ways for that. Found 2 relevant answers on SO - 
- [How to run Django server in daemon mode?](http://stackoverflow.com/questions/14438321/how-to-run-django-server-in-daemon-mode)
- [Django runserver permanent](http://stackoverflow.com/questions/1188542/django-runserver-permanent)

To start the server on boot, you can add it to the 'reboot' entry of Cron scheduler, or just add it to the list of 'Startup Applications'.

**Comment by gangelop** [comment]
I'm already running apache and wsgi on this server for another application, so it looks like this is the way to go for this case. Thnx for the quick reply!

EDIT: I'll try to update this issue when I figure out how to set it up with apache and wsgi.

**Comment by izidormatusov** [comment]
The way how Django apps are deployed is that you put Django behind either [uWSGI](http://uwsgi-docs.readthedocs.org/en/latest/) or [gunicorn](http://gunicorn.org/). To make it really fast, you put in front of it nginx that can serve static files really quickly. Description of that architecture: http://rogueleaderr.com/post/65157477648/the-idiomatic-guide-to-deploying-django-in-production (You can replace nginx with apache and get the same result :)

Or you can us ea service that is going to solve all of those problems for you like [Google App Engine](https://appengine.google.com/) or [Heroku](http://www.heroku.com).
