### ISSUE TITLE
Left action menu is not scrollable

### ISSUE THREAD

**Issue by Kernald** [getting-things-gnome/GTGOnline#2]
On a 1366×768 screen, the left menu doesn't fit. The page is scrollable, but the menu position is fixed, so it doesn't move on scroll.

See the screenshot showing the visible part:
![capture d cran de 2013-09-28 13 45 42](https://f.cloud.github.com/assets/296840/1231122/89443404-2833-11e3-9ae0-021fbac5a4f9.png)

**Comment by parinporecha** [comment]
@Kernald , the page you are viewing is an old demo. The real application is at gtgonline-parinporecha.rhcloud.com/user/landing

I'll remove the demo and redirect the url to the above one :-)
