### ISSUE TITLE
Email containing a '+' is considered invalid

### ISSUE THREAD

**Issue by Kernald** [getting-things-gnome/GTGOnline#3]
Emails containing the + symbol can be used to filter incoming emails, and are absolutely valid. However, GTGOnline doesn't accept them as valid (registration fails).

**Comment by parinporecha** [comment]
@Kernald , GTGOnline uses `ur'[\.\w]{1,}[@]\w+[.]\w+'` to check the validity of an email.
While this is not a perfect way, it does recognize emails having a '@' and '.' in them and have valid username and domain names.

I tried to register a username with '+' on some of the providers, they didn't accept it as valid.
I did find some emails having '-' and other symbols but they are the 'donotreply' ones used in mailinglists.
Please can you give an example of an email of a person having '+' symbol ?

**Comment by Kernald** [comment]
On GMail for example: you can't create a `toto+something@gmail.com`. But if you send an email to `toto+something@gmail.com`, `toto@gmail.com` will receive the email. The `+something` part is not used during transport, but you can use it for filtering purposes for example. I usually register on websites with `myemail+websitename@host.tld`, to know from which site my email address has been taken.
