### ISSUE TITLE
Registration page is not shown entirely

### ISSUE THREAD

**Issue by Kernald** [getting-things-gnome/GTGOnline#4]
When registering with an email not linked to a Gravatar account, fields for first name and last name are added. However, the form is still in a specifically-sized div, with a scrollbar, even if there's still room on the screen. I didn't noticed there was something under the new fields at first. The div should resize.

![login to gtgonline 2013-09-28 13-58-44](https://f.cloud.github.com/assets/296840/1231195/129572a2-283b-11e3-963a-eb542f0c585c.png)

**Comment by parinporecha** [comment]
Patched it in commit 4dcada69d196ffe39f5f11861adeb41560844ec3

Now it'll expand in the space provided
Closing the issue
